version: '3.8'
services:
  web:
    build:
      context: ./
      target: production
    volumes:
      - .:/src
      - /src/node_modules
    command: npm run start
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      REDIS_URL: redis://:a2c74a7c5715448cb7fb7612af38a34b@apn1-supreme-grub-33516.upstash.io:33516
      DATABASE_URL: postgres://sfleyywetapbsy:dab4b94e704b18492fb52c6142340036bb27fec0cd540f25fb3626205b8e512a@ec2-52-205-61-230.compute-1.amazonaws.com:5432/d9j40g56isn3q4
